apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MYSQL_DATABASE: "movie_booking"
  DB_HOST: "mysql.movie-booking.svc.cluster.local"
  DB_NAME: "movie_booking"
  DB_PORT: "3306"