apiVersion: apps/v1
kind: Deployment
metadata:
  name: showtime-service
  namespace: movie-booking
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: showtime-service
  template:
    metadata:
      labels:
        app: showtime-service
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql.movie-booking.svc.cluster.local 3306; do sleep 2; echo "Waiting for MySQL..."; done']
      containers:
      - name: showtime-service
        image: 22i1140/microservices-showtime-service:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: "mysql.movie-booking.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          value: "movie_booking"
        - name: FLASK_ENV
          value: "production"
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
