apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: movie-booking
spec:
  type: NodePort
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30003
      