apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: movie-booking
spec:
  type: NodePort
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001