apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: movie-booking  # Add this
spec:
  type: ClusterIP  # Change from NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306