apiVersion: v1
kind: Service
metadata:
  name: showtime-service
  namespace: movie-booking
spec:
  type: NodePort
  selector:
    app: showtime-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002