apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: movie-booking
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000