---
- name: Deploy Showtime Service
  hosts: microservices
  become: yes
  gather_facts: yes

  vars_files:
    - ../inventories/production/group_vars/all.yml

  roles:
    - showtime-service