---
- name: Full deployment of Movie Booking Application
  hosts: kubernetes_nodes
  become: yes
  gather_facts: yes

  vars_files:
    - ../inventories/production/group_vars/all.yml

  tasks:
    - name: Include prerequisites setup
      include_tasks: setup-prerequisites.yml
      when: inventory_hostname == 'k8s-master'

    - name: Include MySQL deployment
      include_tasks: deploy-mysql.yml
      when: inventory_hostname == 'k8s-master'

    - name: Include User Service deployment
      include_tasks: deploy-user-service.yml
      when: inventory_hostname in ['k8s-node1', 'k8s-node2']

    - name: Include Movie Service deployment
      include_tasks: deploy-movie-service.yml
      when: inventory_hostname in ['k8s-node1', 'k8s-node2']

    - name: Include Showtime Service deployment
      include_tasks: deploy-showtime-service.yml
      when: inventory_hostname in ['k8s-node1', 'k8s-node2']

    - name: Include Booking Service deployment
      include_tasks: deploy-booking-service.yml
      when: inventory_hostname in ['k8s-node1', 'k8s-node2']

    - name: Include Ingress deployment
      include_tasks: deploy-ingress.yml
      when: inventory_hostname == 'k8s-master'

    - name: Verify deployment
      uri:
        url: "http://{{ ingress_host }}/health"
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 10
      delay: 10
      when: inventory_hostname == 'k8s-master'