apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-booking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/microservices.git
    targetRevision: HEAD
    path: k8s_specification  # Path to your Kubernetes manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: movie-booking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true