name: Microservices CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: docker.io
  K8S_NAMESPACE: microservices
  APP_VERSION: ${{ github.sha }}

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest  # Only if you need pytest
        
    - name: Verify installation
      run: |
        pip show Flask mysqlclient requests python-dotenv || exit 1
        echo "✓ All dependencies installed"

    - name: Test imports
      run: |
        python -c "
        try:
            import flask
            from microservices.services import bookings, movies, showtimes, user
            from microservices.database import db_connection
            print('✓ All modules import successfully')
        except ImportError as e:
            print(f'✗ Import failed: {str(e)}')
            exit(1)
        "

  build-and-push:
    needs: setup-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [booking-service, movie-service, showtime-service, user-service]
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and push
      run: |
        docker build \
          -t ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:${{ env.APP_VERSION }} \
          -t ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:latest \
          --build-arg SERVICE_MODULE=${{ matrix.service }} \
          .
        docker push ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:${{ env.APP_VERSION }}
        docker push ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:latest

 
  deploy:
    needs: terraform-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Deployment will be handled separately via ArgoCD"
          echo "Built images:"
          echo "- ${{ env.DOCKER_REGISTRY }}/22i1140/booking-service:${{ env.APP_VERSION }}"
          echo "- ${{ env.DOCKER_REGISTRY }}/22i1140/movie-service:${{ env.APP_VERSION }}"
          echo "- ${{ env.DOCKER_REGISTRY }}/22i1140/showtime-service:${{ env.APP_VERSION }}"
          echo "- ${{ env.DOCKER_REGISTRY }}/22i1140/user-service:${{ env.APP_VERSION }}"